<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Ban all users</h1>
<form method="post">
    <input type="submit" placeholder="BAN ALL USERS">
<#--    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}">-->
</form>
</body>
</html>